force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Serminar__c.field-meta.xml
<CustomField>
    <fullName>Serminar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serminar</label>
    <referenceTo>Serminar__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <externalId>true</externalId>
    <label>Voucher</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Code__c/Promotion_Code__c.object-meta.xml
<CustomObject>
    <label>Promotion Code</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Promotion Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Code__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Code__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Serminar__c/Serminar__c.object-meta.xml
<CustomObject>
    <label>Serminar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serminar__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CH4_BookingController.cls
public without sharing class CH4_BookingController {
    @AuraENabled
    public static Boolean insertBooking(String id, String name, String email, String phone, List<Integer> birthdate, String voucher, String serName, String price) {
        Contact newCt = new Contact();
        newCt.LastName = name;
        newCt.Email = email;
        newCt.Phone = phone;

        if(birthdate.size() == 3){
            newCt.Birthdate = date.newinstance(Integer.valueOf(birthdate[0]), Integer.valueOf(birthdate[1]), Integer.valueOf(birthdate[2]));
        }

        insert newCt;

        Booking__c newBooking = new Booking__c();
        newBooking.Serminar__c = id;
        newBooking.Contact__c = newCt.Id;
        newBooking.Voucher__c = voucher;
        newBooking.Total_Amount__c = Integer.valueOf(price);

        insert newBooking;

        return true;
    }
    @AuraENabled
    public static Decimal validateVoucher(String voucher) {
        Date today = Date.today();
        try {
            return [SELECT Discount__c FROM Promotion_Code__c WHERE Start_Date__c <= :today AND End_Date__c >= :today AND Code__c =: voucher].Discount__c;
        } catch (QueryException ex) {
            // Handle the query exception
            return null;
        }
    }
}