force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Serminar__c.field-meta.xml
<CustomField>
    <fullName>Serminar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serminar</label>
    <referenceTo>Serminar__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Card__c/Contact_Card__c.object-meta.xml
<CustomObject>
    <label>Contact Card</label>
    <nameField>
        <label>Contact Card Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Card</relationshipLabel>
    <relationshipName>Contact_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Card__c/fields/Serminar__c.field-meta.xml
<CustomField>
    <fullName>Serminar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serminar</label>
    <referenceTo>Serminar__c</referenceTo>
    <relationshipLabel>Contact Card</relationshipLabel>
    <relationshipName>Contact_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serminar__c/Serminar__c.object-meta.xml
<CustomObject>
    <label>Serminar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serminar__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CH2_PaymentTriggerHandler.cls
public with sharing class CH2_PaymentTriggerHandler {
    public static void checkPaymentPrice(List<Payment__c> payments){
        
        //GET Bookings ID from all Payments
        Set<Id> bookingIdsSet = new Set<Id>();
        for(Payment__c payment: payments){
            bookingIdsSet.add(payment.Booking__c);
        }
        
        //SET Bookings FROM Database TO Ids
        Map<Id, Booking__c> idToBookingMap = new Map<Id, Booking__c>([SELECT Id, Total_Amount__c, Contact__c, Serminar__c, Serminar__r.Code__c, Serminar__r.Start_Date__c  FROM Booking__c WHERE Id IN : bookingIdsSet]);
        
        //LOOP through Payments Insert List and CHECK condition (Payment price equal to Booking total amount)
        List<Contact_Card__c> ctcardList = new List<Contact_Card__c>();
        for(Payment__c payment: payments){
            Booking__c bk = idToBookingMap.get(payment.Booking__c);
            //Create contact card for valid payment
            if(payment.Price__c == idToBookingMap.get(payment.Booking__c).Total_Amount__c){
                Contact_Card__c ctcard = new Contact_Card__c(
                    Contact__c = bk.Contact__c,
                    Serminar__c = bk.Serminar__c
                );
                ctcardList.add(ctcard);
            }
        }
        
        if(ctcardList.size() > 0){
        	insert ctcardList;
        }
    }
}