force-app/main/default/objects/Contact_Card__c/Contact_Card__c.object-meta.xml
<CustomObject>
    <label>Contact Card</label>
    <nameField>
        <label>Contact Card Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Card</relationshipLabel>
    <relationshipName>Contact_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CH2_ContactCardController.cls
public with sharing class CH2_ContactCardController {
    private ApexPages.StandardController standardController;

    public CH2_ContactCardController(ApexPages.StandardController controller) {
        standardController = controller;

        Contact_Card__c currentRecord = (Contact_Card__c)standardController.getRecord();
        avatar = currentRecord.Contact__r.Avatar__c;
    }

    public Contact_Card__c contactCard { get; set; }
    public String avatar { get; set; }

	
    
}